### PR TITLE
materializePickler macro generates pickler for value classes

### LINKED ISSUE #85: Automatically generate picklers for value classes
Related to #46, it would be great to let boopickle automatically generate picklers for value classes. In my understanding, this would be as simple as defining a `transformPickler` projecting on the single value of that class.

I would like to implement this functionality in the `materializePickler` macro. Would you accept such a PR?

### PR DESCRIPTION
**Pull request by cornerman**
fixes #85

### CODE REVIEW

**Comment by ochrons** [comment]
Can a value class instance be `null`? As that would need to be encoded separately.

**Comment by cornerman** [comment]
@ochrons Good point, but `AnyVal` instances cannot be null:

```scala
scala> val x: AnyVal = null
<console>:11: error: type mismatch;
 found   : Null(null)
 required: AnyVal
Note that implicit conversions are not applicable because they are ambiguous:
 both method RichException in object Predef of type (self: Throwable)RichException
 and method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
 are possible conversion functions from Null(null) to AnyVal
       val x: AnyVal = null
                       ^
Null(null) <: AnyVal?
false
```

```scala
scala> case class Test(x:Int) extends AnyVal
defined class Test
scala> val x: Test = null
<console>:16: error: type mismatch;
 found   : Null(null)
 required: Test
       val x: Test = null
                     ^
Null(null) <: Test?
false
```

**Comment by ochrons** [comment]
Great, then this should be good for merge!

**Comment by cornerman** [comment]
As additional information, this makes it possible to pickle non-case-classes in case of a value class, because we do not need it for the transform pickler.

But you will need a case class if the value class appears within a sealed trait hierarchy, because it is currently needed for getting the correct type for generics (`unifyCaseClassWithTrait`).

**Pull request merged**
