### PR TITLE
Attempt to build for ScalaJs 1.0.0

### PR DESCRIPTION
**Pull request by tbje**
- Allows publishLocal.
- Play-json not yet available for sjs1.
- Workbench not yet available sjs1.
- Open question: how to configure scalaJSOptimizerOptions

### CODE REVIEW

**Comment by tbje** [comment]
Play-json missing part: https://github.com/playframework/play-json/pull/433

**Comment by mathieuleclaire** [comment]
I also have a missing lib: utest 0.6.8 for scalajs 1.0 and for scala 2.11. [utest  for js 2.11 is not kept](https://github.com/lihaoyi/utest/blob/master/build.sc#L83). Question: do we really need to cross compile for 2.11 ?

**Comment by tbje** [comment]
@mathieuleclaire true, I guess it's there mainly for scala-native support?

Actually, utest is available for scala-native 3:
https://mvnrepository.com/artifact/com.lihaoyi/utest

Maybe I should look into removing support for 2.11 on JVM and JS?

**Comment by mathieuleclaire** [comment]
I think we should do this yes.

**Comment by vic** [comment]
Hello, I'm looking forward to upgrade a project of mine to sjs1 and would love this to get merged, is there anything left on this MR that I could help with ?

**Comment by mathieuleclaire** [comment]
We still have the issue concerning scala 2.11. JVM and JS have to be removed for scala 2.11 ? @tbje would you commit this ?

**Comment by strelec** [comment]
I say don't worry about Scala 2.11 for now. It will probably be EOL soon.

If someone needs 2.11 support, they should be welcome to prepare a pull request that adds it back.

**Comment by japgolly** [comment]
I agree. I think another point in favour of doing that is that this library is quite small in scope and I don't see any new features being added soon. It works fantastically and all I foresee is just maintenance for new Scala versions, rather than new features that Scala 2.11 users be sad about not having access to.

**Comment by mathieuleclaire** [comment]
OK, so I remove 2.11 for JS, JVM and Native. We could reintroduce Natvie when the 0.4.0 is released.

**Pull request merged**
